---
- name: Configure k3s master
  hosts: master
  become: true
  tasks:
    - name: Get k3s node-token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Get master node IP
      command: hostname -I
      register: master_ip
      changed_when: false

    - name: Set master IP as fact
      set_fact:
        master_ip: "{{ master_ip.stdout.split()[0] }}"

    - name: Save token for worker nodes
      delegate_to: localhost
      run_once: true
      copy:
        content: "{{ k3s_token.stdout }}"
        dest: ./k3s_token.txt

- name: Configure k3s workers
  hosts: workers
  become: true
  tasks:
    - name: Fetch k3s token from local machine
      delegate_to: localhost
      run_once: true
      slurp:
        src: ./k3s_token.txt
      register: k3s_token_file

    - name: Set k3s token fact
      set_fact:
        k3s_token: "{{ k3s_token_file.content | b64decode | trim }}"

    - name: Join worker nodes to k3s cluster
      shell: |
        K3S_URL=https://{{ hostvars['master'].master_ip }}:6443 K3S_TOKEN={{ k3s_token }} k3s agent &
      args:
        creates: /etc/rancher/k3s/k3s.yaml

- name: Verify cluster nodes
  hosts: master
  become: true
  tasks:
    - name: Wait for worker nodes to join
      shell: "kubectl get nodes --no-headers | wc -l"
      register: node_count
      until: node_count.stdout|int >= 3
      retries: 20
      delay: 10

    - name: Get cluster nodes
      command: kubectl get nodes
      register: cluster_nodes
      changed_when: false

    - name: Show cluster nodes
      debug:
        msg: "{{ cluster_nodes.stdout_lines }}"

