- name: Allow SSH (port 22)
  ufw:
    rule: allow
    port: "22"

- name: Allow HTTP (port 80)
  ufw:
    rule: allow
    port: "80"

- name: Allow HTTPS (port 443)
  ufw:
    rule: allow
    port: "443"

- name: Enable UFW
  ufw:
    state: enabled

