---
- name: Configure single-node k3s Master
  hosts: master
  become: yes
  tasks:
    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure k3s is running
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy kubeconfig
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Replace localhost in kubeconfig with master IP
      replace:
        path: /home/ubuntu/.kube/config
        regexp: '127.0.0.1'
        replace: "{{ ansible_host }}"

