---
- name: Configure single-node k3s Master
  hosts: master
  become: yes
  tasks:
    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure k3s is running
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Change permissions for kubeconfig file
      file:
        path: /etc/rancher/k3s/k3s.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy kubeconfig
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Replace localhost in kubeconfig with master IP
      replace:
        path: /home/ubuntu/.kube/config
        regexp: '127.0.0.1'
        replace: "{{ ansible_host }}"
    - name: Ensure Kubernetes config is accessible
      command: test -f /home/ubuntu/.kube/config
      register: kubeconfig_check
      retries: 5
      delay: 3
      until: kubeconfig_check.rc == 0

    # - name: Test kubectl connection
    #   command: kubectl get nodes
    #   register: kubectl_test
    #   become: yes
    #   retries: 5
    #   delay: 10
    #   until: kubectl_test.rc == 0


    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Check Helm version
      command: helm version
      register: helm_version
      changed_when: false

    - debug:
        msg: "Helm installed successfully: {{ helm_version.stdout }}"
