- name: Deploy Jenkins Pipeline
  hosts: master
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: Get Node IP
      shell: "hostname -I | awk '{print $1}'"
      register: node_ip
      changed_when: false

    - name: Get Jenkins NodePort
      shell: |
        kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml \
        get svc jenkins -n jenkins -o jsonpath='{.spec.ports[0].nodePort}'
      register: jenkins_nodeport
      changed_when: false

    - name: Construct Jenkins URL
      set_fact:
        jenkins_url: "http://{{ node_ip.stdout }}:{{ jenkins_nodeport.stdout }}"

    - name: Display Jenkins URL
      debug:
        msg: "Jenkins is available at {{ jenkins_url }}"

    - name: Save Jenkins URL to file
      copy:
        content: "{{ jenkins_url }}"
        dest: "/mnt/s3/jenkins_url.txt"
        mode: "0644"

    - name: Debug Jenkins Pod Name
      shell: |
        kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml \
        get pod -n jenkins -l app=jenkins -o jsonpath='{.items[0].metadata.name}'
      register: jenkins_pod
      changed_when: false

    - name: Show Jenkins Pod Name
      debug:
        var: jenkins_pod.stdout

    - name: Get Jenkins Admin Password
      shell: |
        kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml \
        exec -n jenkins $(kubectl get pod -n jenkins -l app=jenkins -o jsonpath='{.items[0].metadata.name}') \
        -- cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false
      no_log: true

    - name: Create Jenkins Job using curl
      shell: |
        curl -k -X POST "http://admin:{{ jenkins_password.stdout }}@{{ jenkins_url | regex_replace('http://', '') }}/createItem?name=GitHub-Pipeline"
        -H "Content-Type: application/xml"
        -H "Authorization: Bearer {{ lookup('env', 'AWS_TOKEN') }}"
        --data-binary "@{{ playbook_dir }}/pipeline.xml"
      register: jenkins_job_response
      failed_when: jenkins_job_response.rc != 0

        #    - name: Create Jenkins Job using curl
        #shell: >
        #curl -k -X POST "http://admin:{{ jenkins_password.stdout }}@{{ jenkins_url | regex_replace('http://', '') }}/createItem?name=GitHub-Pipeline" 
        #-H "Content-Type: application/xml" 
        #--data-binary "@{{ playbook_dir }}/pipeline.xml"
        #register: jenkins_job_response
        #failed_when: jenkins_job_response.rc != 0

    - name: Display Jenkins Job Response
      debug:
        var: jenkins_job_response.stdout
