- name: Deploy Jenkins Pipeline
  hosts: master
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    git_repo_url: "https://github.com/ionmariana531/sciitdevops.git"
    git_branch: "add-terraform-github-actions-Mariana-fe"
  tasks:

    - name: Get Node IP
      shell: "hostname -I | awk '{print $1}'"
      register: node_ip
      changed_when: false

    - name: Get Jenkins NodePort (async)
      shell: |
        kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml \
        get svc jenkins -n jenkins -o jsonpath='{.spec.ports[0].nodePort}'
      register: jenkins_nodeport_job
      changed_when: false
      async: 300
      poll: 0

    - name: Wait for async job
      async_status:
        jid: "{{ jenkins_nodeport_job.ansible_job_id }}"
      register: jenkins_nodeport
      until: jenkins_nodeport.finished
      retries: 10
      delay: 5

    - name: Construct Jenkins URL
      set_fact:
        jenkins_url: "http://{{ node_ip.stdout }}:{{ jenkins_nodeport.stdout | default('none') }}"

    - name: Display Jenkins URL
      debug:
        msg: "Jenkins is available at {{ jenkins_url }}"

    - name: Save Jenkins URL to file
      copy:
        content: "{{ jenkins_url }}"
        dest: "/mnt/s3/jenkins_url.txt"
        mode: "0644"

    - name: Get Jenkins Admin Password
      shell: |
        POD_NAME=$(kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml \
        get pod -n jenkins -l app=jenkins -o jsonpath='{.items[0].metadata.name}')
        
        kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml \
        exec -n jenkins $POD_NAME -- cat /var/jenkins_home/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - name: Clone the repository to get pipeline.xml
      git:
        repo: "{{ git_repo_url }}"
        dest: "/home/ubuntu/jenkins_repo"
        version: "{{ git_branch }}"
        update: yes
      register: git_clone_result

    - name: Check if pipeline.xml exists
      stat:
        path: "/home/ubuntu/jenkins_repo/pipeline.xml"
      register: pipeline_file

    - name: Create Jenkins Job using Ansible module
      community.general.jenkins_job:
        url: "{{ jenkins_url }}"
        user: "admin"
        password: "{{ jenkins_password.stdout }}"
        name: "GitHub-Pipeline"
        config: "{{ lookup('file', '/home/ubuntu/jenkins_repo/pipeline.xml') }}"
      when: pipeline_file.stat.exists
