---
- name: Configure AWS VMs
  hosts: servers
  become: true
  roles:
    - firewall
    - ssh_setup
    - docker
    - git

- name: Configure k3s Cluster Master
  hosts: master
  become: true
  roles:
    - k3s_master  # Asigură-te că ai creat rolul k3s_master pentru configurarea masterului

- name: Configure k3s Cluster Worker
  hosts: worker
  become: true
  roles:
    - k3s_worker  # Asigură-te că ai creat rolul k3s_worker pentru configurarea workerului

