name: "Terraform CI/CD"

on:
  push:
    branches:
      - add-terraform-github-actions-Mariana-fe

  workflow_dispatch:



jobs:
  provision-ec2:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: 'eu-west-1'

      # Terraform Setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Save instance IPs and create inventory file for Ansible
      - name: Save instance IPs and create inventory
        run: |
          INSTANCE_IPS=$(terraform output -json instance_ips)
          echo "$INSTANCE_IPS" | jq -r '.[]' > ansible/instance-ips.txt
          echo "[servers]" > ansible/inventory.ini
          while IFS= read -r ip; do
            echo "$ip ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/aws-key.pem" >> ansible/inventory.ini
          done < ansible/instance-ips.txt

      # Wait for SSH to be available (with retry and progressive wait)
      - name: Wait for SSH to be available
        run: |
          for ip in $(cat ansible/instance-ips.txt); do
            echo "⏳ Waiting for SSH on $ip..."
            SECONDS=0
            RETRIES=10
            for i in $(seq 1 $RETRIES); do
              if nc -z $ip 22; then
                echo "✅ SSH is available on $ip!"
                break
              fi
              echo "⏳ SSH is not available, retrying in $((i * 10)) seconds..."
              sleep $((i * 10))  # Progresivitatea crește timpul de așteptare la fiecare retry
              if [ $i -eq $RETRIES ]; then
                echo "❌ Timeout: SSH is not available on $ip after $((i * 10)) seconds."
                exit 1
              fi
            done
          done




      #  Add SSH Key from GitHub Secrets
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/aws-key.pem
          chmod 600 ~/.ssh/aws-key.pem

      # Test SSH connection (with retries)
      - name: Test SSH connection
        run: |
          INSTANCE_IP=$(terraform output -json instance_ips | jq -r '.[0]')
          echo "Trying to SSH into $INSTANCE_IP"
          RETRIES=5
          SUCCESS=0
          for i in $(seq 1 $RETRIES); do
            if ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/aws-key.pem ubuntu@$INSTANCE_IP; then
              SUCCESS=1
              break
            else
              echo "❌ Attempt $i failed. Retrying in $((i * 20)) seconds..."
              sleep $((i * 20))  # Creștem timpul de așteptare la fiecare încercare
            fi
          done

          if [ $SUCCESS -eq 0 ]; then
            echo "❌ SSH connection failed after $RETRIES attempts."
            exit 1
          fi
          echo "✅ SSH connection successful!"

      # Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install -y ansible
          ansible --version

      # Run Ansible Playbook
      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yaml -vvv

