name: "Terraform CI/CD"

on:
  push:
    branches:
      - add-terraform-github-actions-Mariana-fe
  workflow_dispatch:

jobs:
  provision-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: 'eu-west-1'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Debug Terraform Output
        run: terraform output -json

      - name: Generate Ansible Inventory
        run: |
          INSTANCE_IP=$(terraform output -json instance_ips | jq -r '.[0]')
          echo "[master]" > ansible/inventory.ini
          echo "$INSTANCE_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/app-ssh-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ansible/inventory.ini
          cat ansible/inventory.ini

      - name: Add SSH Keys on Runner
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/app-ssh-key.pem
          chmod 600 ~/.ssh/app-ssh-key.pem

      - name: Wait for SSH to become available
        run: |
          INSTANCE_IP=$(terraform output -json instance_ips | jq -r '.[0]')
          for i in {1..10}; do
            if nc -zv $INSTANCE_IP 22; then
              echo "SSH is available on $INSTANCE_IP"
              exit 0
            fi
            echo "Retrying SSH connection ($i/10)..."
            sleep 10
          done
          echo "SSH not available after multiple attempts."
          exit 1

      - name: Install Ansible on EC2
        run: |
          INSTANCE_IP=$(terraform output -json instance_ips | jq -r '.[0]')
          ssh -i ~/.ssh/app-ssh-key.pem ubuntu@$INSTANCE_IP << 'EOF'
            sudo apt update
            sudo apt install -y ansible
          EOF

      - name: Install Ansible collections on the runner
        run: |
          ansible-galaxy collection install kubernetes.core
          ansible-galaxy collection install -r ./ansible/Module2/collection-requirements.yaml

      - name: Run Ansible Playbooks on EC2
        run: |
          INSTANCE_IP=$(terraform output -json instance_ips | jq -r '.[0]')
          echo "[master]" > inventory.ini
          echo "$INSTANCE_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/app-ssh-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory.ini

          # Rulăm playbook-urile pe instanța EC2
          ansible-playbook -i inventory.ini ansible/playbook.yaml -vvv
          ansible-playbook -i inventory.ini ansible/Module2/configure_k3s_cluster.yaml -vvv
          ansible-playbook -i inventory.ini ansible/Module2/setup_argocd_jenkins.yaml -vvv
