name: "Terraform CI/CD"

on: push

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/sciitdevops/sciitdevops/terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'add-terraform-github-actions-Mariana-fe'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.2  # Ajustează la versiunea ta
      - name: run
        run: |
          pwd
          ls -ltr 

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Verifică directorul curent
        run: pwd

      - name: Debug AWS Credentials
        run: |
          echo "AWS Access Key ID: $AWS_ACCESS_KEY_ID"
          echo "AWS Secret Access Key: $AWS_SECRET_ACCESS_KEY"
          aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1"

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1" # Regiunea de AWS

      - name: AWS Identity Debug
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1" # Regiunea de AWS

      - name: Debug Terraform Apply
        run: |
          echo "Verificăm conținutul tfplan înainte de apply"
          ls -l tfplan  # Verifică dacă fișierul tfplan există
          terraform show tfplan  # Afișează conținutul planului Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}          
          AWS_REGION: "eu-west-1" # Regiunea de AWS

      - name: Terraform Apply
        if: github.ref == 'add-terraform-github-actions-Mariana-fe' 
        run: terraform apply --auto-approve tfplan 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1" # Regiunea de AWS

      - name: Debug Terraform Apply Output
        run: echo "Terraform Apply Output" && terraform apply -auto-approve tfplan || echo "Terraform Apply Failed"


